name: Trees from Seed CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn --frozen-lockfile
    - name: Code tests
      run: yarn test:code
      env:
        CI: true
    - name: E2E Cypress tests
      uses: cypress-io/github-action@v1
      with:
        start: yarn serve
        wait-on: http://localhost:8080/
        config_file: cypress.json
        spec: "tests/e2e/**/*"
      env:
        CYPRESS_baseUrl: http://localhost:8080/
        CI: true
